Fixed bug in addHost
Fixed the bug where the comparison operator in line 28 will always lead to exit of the script.

diff --git a/addHost b/addHost
--- a/addHost
+++ b/addHost
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 MAC=$3
+MAC_valid=0
 
 if [ -z "$2" ] || [ -z "$1" ]
 then
@@ -24,10 +25,17 @@ fi
 
 
 re="^([a-fA-F0-9]{2}:){5}[a-fA-F0-9]{2}$"
-[[ $MAC =~ $re ]] && echo "Adding record to config" || echo "Invalid MAC" && exit 1
+[[ $MAC =~ $re ]] && MAC_valid=1 || MAC_valid=0
 
 
 
-echo -e "host $1{\n  hardware ethernet $MAC;\n  fixed-address $2; \n}" >> /etc/dhcp/dhcpd.conf
+if [ "$MAC_valid" -eq 0 ]
+then
+        echo "MAC address invalid"
+        exit 1
+else
 
-systemctl restart isc-dhcp-server
+        echo -e "host $1{\n  hardware ethernet $MAC;\n  fixed-address $2; \n}"  >>  /etc/dhcp/dhcpd.conf
+
+        systemctl restart isc-dhcp-server
+fi
